
project_id = "hbmismnzmocjazaiicdu"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[realtime]
webhook_relay = true

[storage]
backend = "file"
file.storage_backend = "file"
file.upload_dir = "storage"

[vector]
enable_libsql = false

[functions]
strict_get_region_invocation = true

[functions.shopify-sync]
verify_jwt = false

[functions.shopify-all-open-unfulfilled-partial]
verify_jwt = false

[functions.shopify-all-open-unfulfilled-partial_v2]
verify_jwt = false

[functions.shopify-database-cleanup]
verify_jwt = false

[functions.shopify-import-single-order]
verify_jwt = false

[functions.shopify-locations-sync]
verify_jwt = false

[functions.shopify-locations-sync-v2]
verify_jwt = false

[functions.shopify-locations-sync-v3]
verify_jwt = false

[functions.shopify-complete-refresh]
verify_jwt = false
