
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbmismnzmocjazaiicdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhibWlzbW56bW9jamF6YWlpY2R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNjk1MDcsImV4cCI6MjA1OTg0NTUwN30.gnCYxUmbL0nZMmmiZp641fkEjv7bbitUNIFK2LMjMXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'iron-city-auth-token',
  }
});
